server:
  port: 2334
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:Rocky}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    youtubePlaylistLoadLimit: 200
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - WEB
      - MUSIC
      - ANDROID_VR
      - WEBEMBEDDED

  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: true
      applemusic: false
      deezer: false
      yandexmusic: false
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID:f75a4775bdb6438ca0a706b48123d044}
      clientSecret: ${SPOTIFY_CLIENT_SECRET:565222346b3346738931226b9083d865}
      countryCode: "PE"
      playlistLoadLimit: 200
      albumLoadLimit: 100

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO
