services:
  - type: web
    name: lavalink
    runtime: docker
    repo: https://github.com/Botsdiscordv1/ProyectosBotsAntigravity
    branch: main
    rootDir: lavalink-render
    dockerfilePath: Dockerfile
    envVars:
      - key: LAVALINK_PASSWORD
        sync: false
    healthCheckPath: /
    healthCheckPort: 10000
