const express = require("express");
const jwt = require("jsonwebtoken");
const bcrypt = require("bcryptjs");
const passport = require("passport");
const DiscordStrategy = require("passport-discord").Strategy;
const GoogleStrategy = require("passport-google-oauth20").Strategy;
const User = require("../models/User");
const { requireApiKey, requireAuth } = require("./middleware/auth");
const db = require("../database");
const { DiscordUser } = db;
const {
  findLikedSongByUrl,
  updateLikedSongUrl,
  getAllLikedSongsWithBadUrls,
  BAD_URI_REGEX,
} = db;
const { getLyrics } = require("../services/lrclib");
const spotify = require("../services/spotify");

const axios = require("axios");
const play = require("play-dl");

const { spawn } = require("child_process");
const path = require("path");
const fs = require("fs");


const YTDLP_BIN = process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp";
const YTDLP_PATH = path.join(__dirname, "..", "..", "node_modules", "@distube", "yt-dlp", "bin", YTDLP_BIN);
const COOKIES_PATH = path.join(__dirname, "..", "..", "cookies.txt");

// Asegurar permisos de ejecución de yt-dlp en Linux
if (process.platform !== "win32") {
  try {
    if (fs.existsSync(YTDLP_PATH)) {
      fs.chmodSync(YTDLP_PATH, "755");
      console.log("[SERVER] yt-dlp execute permissions verified");
    }
  } catch (err) {
    console.warn(`[SERVER] Failed to chmod yt-dlp: ${err.message}`);
  }
}

// Utilidades para manejar cookies de YouTube
function getNetscapeCookies(input) {
  if (!input) return "";
  const trimmed = input.trim();
  if (trimmed.startsWith("# Netscape") || trimmed.includes("\t")) {
    return trimmed;
  }
  const lines = ["# Netscape HTTP Cookie File", "# Generated by Server-Music"];
  const pairs = trimmed.split(";");
  for (const pair of pairs) {
    const eqIdx = pair.indexOf("=");
    if (eqIdx === -1) continue;
    const name = pair.slice(0, eqIdx).trim();
    const value = pair.slice(eqIdx + 1).trim();
    if (name && value) {
      const expiry = Math.floor(Date.now() / 1000) + 10 * 365 * 24 * 60 * 60;
      lines.push(`.youtube.com\tTRUE\t/\tTRUE\t${expiry}\t${name}\t${value}`);
    }
  }
  return lines.join("\n");
}

function parseNetscapeCookiesToHeader(content) {
  if (!content) return "";
  const lines = content.split("\n");
  const cookies = [];
  for (const line of lines) {
    if (!line.trim() || line.startsWith("#")) continue;
    const parts = line.split("\t");
    if (parts.length >= 7) {
      const name = parts[5].trim();
      const value = parts[6].trim();
      cookies.push(`${name}=${value}`);
    }
  }
  return cookies.join("; ");
}

let youtubeCookieString = "";

if (process.env.YOUTUBE_COOKIES) {
  const envContent = process.env.YOUTUBE_COOKIES.trim();
  if (envContent.startsWith("# Netscape") || envContent.includes("\t")) {
    try {
      fs.writeFileSync(COOKIES_PATH, envContent, "utf8");
      youtubeCookieString = parseNetscapeCookiesToHeader(envContent);
      console.log("[COOKIES] Loaded Netscape cookies from YOUTUBE_COOKIES env var and wrote to cookies.txt");
    } catch (err) {
      console.error("[COOKIES] Failed to write Netscape cookies.txt:", err.message);
    }
  } else {
    youtubeCookieString = envContent;
    const netscapeContent = getNetscapeCookies(envContent);
    try {
      fs.writeFileSync(COOKIES_PATH, netscapeContent, "utf8");
      console.log("[COOKIES] Converted Header cookies from YOUTUBE_COOKIES env var and wrote to cookies.txt");
    } catch (err) {
      console.error("[COOKIES] Failed to write converted cookies.txt:", err.message);
    }
  }
} else if (fs.existsSync(COOKIES_PATH)) {
  try {
    const fileContent = fs.readFileSync(COOKIES_PATH, "utf8");
    youtubeCookieString = parseNetscapeCookiesToHeader(fileContent);
    console.log("[COOKIES] Loaded cookies from local cookies.txt");
  } catch (err) {
    console.error("[COOKIES] Failed to read local cookies.txt:", err.message);
  }
}

if (youtubeCookieString) {
  try {
    play.setToken({
      youtube: {
        cookie: youtubeCookieString
      }
    });
    console.log("[COOKIES] play-dl configured with YouTube cookies.");
  } catch (err) {
    console.error("[COOKIES] Failed to configure play-dl with cookies:", err.message);
  }
}

function ytDlpGetUrl(videoUrl) {
  return new Promise((resolve, reject) => {
    const args = [
      videoUrl,
      "-f", "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio/best",
      "-g",
      "--no-warnings",
      "--extractor-retries", "2",
      "--sleep-requests", "0.5",
      "--sleep-interval", "1",
      "--max-sleep", "3",
    ];
    if (fs.existsSync(COOKIES_PATH)) {
      args.push("--cookies", COOKIES_PATH);
    }
    const executionTimeout = IS_RENDER ? 12000 : 45000;
    const proc = spawn(YTDLP_PATH, args, { timeout: executionTimeout });
    let stdout = "", stderr = "";
    proc.stdout.on("data", d => stdout += d);
    proc.stderr.on("data", d => stderr += d);
    proc.on("close", code => {
      const url = stdout.toString().trim();
      if (code === 0 && url) {
        resolve(url);
      } else {
        reject(new Error(stderr || `Exit code ${code}`));
      }
    });
    proc.on("error", reject);
  });
}

const STREAM_CACHE_MAX = 200;
const IS_RENDER = !!process.env.RENDER;

const { getCached, setCached } = (() => {
  const DB_PATH = path.join(__dirname, "..", "..", "stream-cache.json");

  function loadDisk() {
    if (IS_RENDER) return {}; // Render tiene FS efímero, no vale la pena
    try { return JSON.parse(fs.readFileSync(DB_PATH, "utf8")); }
    catch { return {}; }
  }

  function saveDisk(data) {
    if (IS_RENDER) return;
    try { fs.writeFileSync(DB_PATH, JSON.stringify(data), "utf8"); } catch {}
  }

  const disk = loadDisk();
  const mem = new Map();

  // Migrate disk → mem on startup, mantener solo las más recientes
  const validEntries = Object.entries(disk)
    .filter(([, v]) => Date.now() - v.ts < 7 * 24 * 60 * 60 * 1000)
    .sort((a, b) => b[1].ts - a[1].ts)
    .slice(0, STREAM_CACHE_MAX);
  for (const [k, v] of validEntries) mem.set(k, v);
  if (Object.keys(disk).length !== mem.size) saveDisk(Object.fromEntries(mem));

  function evictLRU() {
    if (mem.size <= STREAM_CACHE_MAX) return;
    const sorted = [...mem.entries()].sort((a, b) => a[1].ts - b[1].ts);
    for (let i = 0; i < sorted.length - STREAM_CACHE_MAX; i++) mem.delete(sorted[i][0]);
  }

  // Flush to disk every 60s (solo en local)
  if (!IS_RENDER) setInterval(() => { saveDisk(Object.fromEntries(mem)); }, 60_000);

  return {
    getCached: (key) => {
      const e = mem.get(key);
      if (!e) return null;

      // Si la URL contiene un parámetro de expiración (como las de YouTube)
      if (e.url && e.url.includes("expire=")) {
        try {
          const decoded = e.url.includes("%") ? decodeURIComponent(e.url) : e.url;
          const match = decoded.match(/[?&]expire=(\d+)/);
          if (match) {
            const expireSec = parseInt(match[1], 10);
            const nowSec = Math.floor(Date.now() / 1000);
            if (nowSec >= expireSec - 600) {
              mem.delete(key);
              return null;
            }
            return e.url;
          }
        } catch (err) {}
      }

      // Tiempo de vida por defecto para otros tipos de URL (7 días)
      const isValid = Date.now() - e.ts < 7 * 24 * 60 * 60 * 1000;
      if (!isValid) {
        mem.delete(key);
        return null;
      }
      return e.url;
    },
    setCached: (key, url) => {
      mem.set(key, { url, ts: Date.now() });
      evictLRU();
    },
  };
})();

const searchCache = new Map();
const SEARCH_CACHE_TTL = 5 * 60 * 1000;  // 5 min
const SEARCH_CACHE_MAX = 50;              // máx 50 búsquedas
function cleanCache(cache, ttl, max) {
  const now = Date.now();
  for (const [key, entry] of cache) {
    if (now - entry.ts > ttl) cache.delete(key);
  }
  if (cache.size > max) {
    const entries = [...cache.entries()].sort((a, b) => a[1].ts - b[1].ts);
    for (let i = 0; i < entries.length - max; i++) cache.delete(entries[i][0]);
  }
}
setInterval(() => cleanCache(searchCache, SEARCH_CACHE_TTL, SEARCH_CACHE_MAX), 60_000);

function extractVideoId(input) {
  if (!input) return null;
  const s = input.trim();
  if (/^[a-zA-Z0-9_-]{11}$/.test(s)) return s;
  try {
    const url = new URL(s);
    if (url.hostname.includes("youtube")) return url.searchParams.get("v");
    if (url.hostname === "youtu.be") return url.pathname.slice(1).split("?")[0] || null;
  } catch {}
  return null;
}

async function extractVideoIdFromLavalink(input) {
  try {
    // lavasrc format: <base64>||<plugin_data>
    const track = input.includes("||") ? input.split("||")[0] : input;
    if (!/^[A-Za-z0-9+/=]+$/.test(track)) return null;
    const res = await axios.get(`${LAVALINK_PROTO}://${LAVALINK_HOST}:${LAVALINK_PORT}/v4/decodetrack`, {
      params: { encodedTrack: track },
      headers: { Authorization: LAVALINK_AUTH },
      timeout: 5000,
    });
    return res.data?.info?.identifier || null;
  } catch {
    return null;
  }
}

const failedVideoIds = new Map();
setInterval(() => {
  for (const [id, ts] of failedVideoIds) {
    if (Date.now() - ts > 3600_000) failedVideoIds.delete(id);
  }
}, 600_000); // limpiar cada 10 min en lugar de cada 1 min

let streamQueuePromise = Promise.resolve();

async function resolveStreamUrl(identifier, req = null) {
  if (!identifier || typeof identifier !== "string") return null;

  // URL de audio directa (Deezer, etc.) → proxylar por el backend
  if (/^https?:\/\/.+\.(mp3|m4a|ogg|wav|flac|opus)(\?|$)/i.test(identifier)) {
    const hash = "proxy:" + identifier.slice(0, 40);
    const cached = getCached(hash);
    if (cached) return cached;
    if (req) {
      const proxyUrl = `${req.protocol}://${req.get("host")}/api/proxy/audio?url=${encodeURIComponent(identifier)}`;
      setCached(hash, proxyUrl);
      return proxyUrl;
    }
    // Sin req (warm en background), devolver directo
    setCached(hash, identifier);
    return identifier;
  }

  let videoId = extractVideoId(identifier);
  if (!videoId) videoId = await extractVideoIdFromLavalink(identifier);
  if (!videoId) return null;

  if (failedVideoIds.has(videoId)) return null;

  const cached = getCached(videoId);
  if (cached) return cached;

  // Encolar la resolución para garantizar que nunca se ejecuten procesos concurrentes de yt-dlp/play-dl
  return new Promise((resolve) => {
    streamQueuePromise = streamQueuePromise.then(async () => {
      try {
        const secondaryCache = getCached(videoId);
        if (secondaryCache) {
          resolve(secondaryCache);
          return;
        }
        const streamUrl = await doResolveStreamUrl(videoId, req);
        resolve(streamUrl);
      } catch (err) {
        resolve(null);
      } finally {
        // Liberar memoria forzando GC explícito en Render
        if (global.gc) {
          try { global.gc(); } catch {}
        }
      }
    });
  });
}

async function resolveViaCobalt(videoId) {
  const instances = [
    "https://apicobalt.mgytr.top",
    "https://cobalt.alpha.wolfy.love",
    "https://lime.clxxped.lol",
    "https://api.qwkuns.me"
  ];
  
  for (const instance of instances) {
    try {
      console.log(`[stream] Trying Cobalt instance: ${instance} for video ${videoId}`);
      const res = await axios.post(instance, {
        url: `https://www.youtube.com/watch?v=${videoId}`,
        audioFormat: "best",
        downloadMode: "audio"
      }, {
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
        },
        timeout: 8000
      });
      
      if (res.status === 200 && res.data && res.data.url) {
        console.log(`[stream] Success resolving ${videoId} via Cobalt (${instance})`);
        return res.data.url;
      }
    } catch (err) {
      console.warn(`[stream] Cobalt instance ${instance} failed: ${err.message}`);
    }
  }
  return null;
}

async function resolveViaInvidious(videoId) {
  const instances = [
    "https://yewtu.be",
    "https://invidious.flokinet.to",
    "https://invidious.projectsegfaut.de",
    "https://inv.tux.im",
    "https://invidious.privacydev.net",
    "https://iv.melmac.space"
  ];

  for (const instance of instances) {
    try {
      console.log(`[stream] Trying Invidious instance: ${instance} for video ${videoId}`);
      const res = await axios.get(`${instance}/api/v1/videos/${videoId}`, { timeout: 6000 });
      if (res.data && res.data.adaptiveFormats) {
        // Encontrar formatos de audio
        const audioFormats = res.data.adaptiveFormats.filter(f => f.type && f.type.startsWith("audio/"));
        if (audioFormats.length > 0) {
          // Ordenar por bitrate descendente para obtener la mejor calidad
          audioFormats.sort((a, b) => (parseInt(b.bitrate) || 0) - (parseInt(a.bitrate) || 0));
          const bestAudio = audioFormats[0];
          if (bestAudio.url) {
            console.log(`[stream] Success resolving ${videoId} via Invidious (${instance})`);
            return bestAudio.url;
          }
        }
      }
    } catch (err) {
      console.warn(`[stream] Invidious instance ${instance} failed: ${err.message}`);
    }
  }
  return null;
}

async function doResolveStreamUrl(videoId, req = null) {
  const hasCookies = fs.existsSync(COOKIES_PATH);

  // 1) En Render, si no hay cookies, saltamos directo a Cobalt para máxima velocidad y evitar bloqueos
  if (IS_RENDER && !hasCookies) {
    console.log(`[stream] Running on Render without cookies. Prioritizing Cobalt for ${videoId}`);
    try {
      const streamUrl = await resolveViaCobalt(videoId);
      if (streamUrl) {
        setCached(videoId, streamUrl);
        return streamUrl;
      }
    } catch (e) {
      console.warn(`[stream] Cobalt failed on Render: ${e.message}`);
    }
    
    // Fallback: Invidious
    try {
      const streamUrl = await resolveViaInvidious(videoId);
      if (streamUrl) {
        setCached(videoId, streamUrl);
        return streamUrl;
      }
    } catch (e) {
      console.warn(`[stream] Invidious fallback failed on Render: ${e.message}`);
    }
    
    failedVideoIds.set(videoId, Date.now());
    return null;
  }

  // 2) Caso estándar (Local o Render con cookies): intentamos la jerarquía normal
  
  // A. yt-dlp
  try {
    const streamUrl = await ytDlpGetUrl(`https://www.youtube.com/watch?v=${videoId}`);
    if (streamUrl) {
      setCached(videoId, streamUrl);
      return streamUrl;
    }
  } catch (e) {
    console.warn(`[stream] yt-dlp failed for ${videoId}: ${e.message}`);
  }

  // B. Cobalt (como fallback secundario ultra-veloz si yt-dlp falla)
  try {
    const streamUrl = await resolveViaCobalt(videoId);
    if (streamUrl) {
      setCached(videoId, streamUrl);
      return streamUrl;
    }
  } catch (e) {
    console.warn(`[stream] Cobalt fallback failed for ${videoId}: ${e.message}`);
  }

  // C. play-dl (solo si no es Render, para evitar hangs de IP blacklist)
  if (!IS_RENDER) {
    try {
      const info = await play.video_info(`https://www.youtube.com/watch?v=${videoId}`).catch(async () => {
        const search = await play.search(videoId, { limit: 1 });
        return search[0] ? await play.video_info(search[0].url) : null;
      });
      if (info) {
        const stream = await play.stream_from_info(info, { quality: 2, discordPlayerCompatibility: true });
        if (stream?.url) {
          setCached(videoId, stream.url);
          return stream.url;
        }
      }
    } catch (e) {
      console.warn(`[stream] play-dl failed for ${videoId}: ${e.message}`);
    }
  }

  // D. Invidious fallback
  try {
    const streamUrl = await resolveViaInvidious(videoId);
    if (streamUrl) {
      setCached(videoId, streamUrl);
      return streamUrl;
    }
  } catch (e) {
    console.warn(`[stream] Invidious fallback failed for ${videoId}: ${e.message}`);
  }

  failedVideoIds.set(videoId, Date.now());
  return null;
}

const LAVALINK_HOST = process.env.LAVALINK_HOST || "localhost";
const LAVALINK_PORT = Number(process.env.LAVALINK_PORT) || 2333;
const LAVALINK_SECURE = process.env.LAVALINK_SECURE === "true";
const LAVALINK_PROTO = LAVALINK_SECURE ? "https" : "http";
const LAVALINK_AUTH = process.env.LAVALINK_PASSWORD || "youshallnotpass";

const app = express();
app.set("trust proxy", 1); // Render usa proxy reverso con SSL
app.use(express.json());
app.use(passport.initialize());

// Logger simple para debug en Render
app.use((req, res, next) => {
  console.log(`[${req.method}] ${req.url}`);
  next();
});

// Root Health Check (Para Render)
app.get("/", (req, res) => {
  res.send("Android Music Backend is running");
});

// API Health Check (Para el App Android)
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", service: "music-api", extractor: "yt-dlp (android client)" });
});

// Proxy de audio (Deezer, Spotify, YouTube, etc.) — soporta Range/Partial Content
app.get("/api/proxy/audio", async (req, res) => {
  const targetUrl = req.query.url;
  if (!targetUrl) return res.status(400).json({ error: "Missing url" });

  const headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
  };
  if (targetUrl.includes("deezer.com")) {
    headers["Referer"] = "https://deezer.com/";
  }
  if (req.headers.range) {
    headers["Range"] = req.headers.range;
  }

  try {
    const response = await axios.get(targetUrl, {
      responseType: "stream",
      headers: headers,
      timeout: 15000,
      validateStatus: (status) => (status >= 200 && status < 300) || status === 206,
    });

    res.status(response.status);
    if (response.headers["content-type"]) res.set("Content-Type", response.headers["content-type"]);
    if (response.headers["content-length"]) res.set("Content-Length", response.headers["content-length"]);
    if (response.headers["content-range"]) res.set("Content-Range", response.headers["content-range"]);
    if (response.headers["accept-ranges"]) res.set("Accept-Ranges", response.headers["accept-ranges"]);

    response.data.pipe(res);

    // Evitar fugas de sockets destruyendo el flujo de entrada cuando el cliente cierra la petición
    res.on("close", () => {
      if (response && response.data && typeof response.data.destroy === "function") {
        response.data.destroy();
      }
    });
  } catch (e) {
    console.error("Proxy error:", e.message);
    res.status(502).json({ error: "Proxy fetch failed: " + (e.message || e) });
  }
});

const SOURCE_MAP = {
  deezer: "ytmsearch",
  spotify: "ytmsearch",
  youtube: "ytmsearch",
  ytmsearch: "ytmsearch",
  ytsearch: "ytsearch",
  soundcloud: "scsearch",
};

app.get("/api/search", requireApiKey, async (req, res) => {
  try {
    const q = req.query.q;
    const source = SOURCE_MAP[req.query.source] || "ytmsearch";
    if (!q) return res.status(400).json({ error: "Missing query parameter 'q'" });

    const cacheKey = `${source}:${q}`;
    const cached = searchCache.get(cacheKey);
    if (cached && Date.now() - cached.ts < SEARCH_CACHE_TTL) {
      return res.json(cached.data);
    }

    const tracks = await searchLavalink(source, q);
    if (!tracks.length) return res.json({ query: q, source, tracks: [] });

    const result = { query: q, source, tracks };
    searchCache.set(cacheKey, { data: result, ts: Date.now() });
    res.json(result);

    // Procesar en background
    setImmediate(async () => {
      // 1) Pre-resolver streams en background (SOLO si no es Render, para ahorrar RAM)
      if (!IS_RENDER) {
        for (const track of tracks.slice(0, 3)) {
          if (track.uri) {
            try { await resolveStreamUrl(track.uri, req); } catch (e) {}
          }
        }
      }
      // 2) Enriquecer portadas con Deezer en background
      try {
        const enriched = await enrichArtworkWithDeezer(tracks);
        if (enriched.length) {
          result.tracks = enriched;
          searchCache.set(cacheKey, { data: result, ts: Date.now() });
        }
      } catch (e) {}
    });
  } catch (err) {
    console.error("Search Error:", err.message);
    res.status(500).json({ error: err.message });
  }
});


async function searchLavalink(source, query) {
  const url = `${LAVALINK_PROTO}://${LAVALINK_HOST}:${LAVALINK_PORT}/v4/loadtracks?identifier=${encodeURIComponent(source + ":" + query)}`;
  const response = await axios.get(url, {
    headers: { Authorization: LAVALINK_AUTH },
    timeout: 15000,
  });
  const tracks = (response.data?.data || []).map(t => ({
    id: t.info?.identifier,
    encoded: t.encoded,
    title: t.info?.title,
    artist: t.info?.author,
    author: t.info?.author,
    duration: t.info?.duration,
    uri: t.info?.uri,
    artworkUrl: t.info?.artworkUrl,
    thumbnail: t.info?.artworkUrl,
    source: t.info?.sourceName,
    album: t.info?.albumName || t.pluginInfo?.albumName || null,
    albumUrl: t.pluginInfo?.albumUrl || null,
    isrc: t.info?.isrc || t.pluginInfo?.isrc || null,
    explicit: false,
  }));
  await enrichExplicitWithDeezerISRC(tracks);
  return tracks;
}

async function enrichExplicitWithDeezerISRC(tracks) {
  // Limitar a los primeros 6 con ISRC para no saturar memoria/sockets
  const targets = tracks.filter(t => t.isrc).slice(0, 6);
  const lookups = targets.map(async (track) => {
    try {
      const res = await axios.get(`https://api.deezer.com/track/isrc:${track.isrc}`, { timeout: 3000 });
      if (res.data?.explicit_lyrics !== undefined) track.explicit = res.data.explicit_lyrics;
    } catch (e) {}
  });
  await Promise.allSettled(lookups);
}

async function enrichArtworkWithDeezer(tracks) {
  const enriched = [...tracks];
  // Limitar enriquecimiento a los primeros 6 resultados para ahorrar RAM y peticiones HTTP
  const limit = Math.min(enriched.length, 6);
  for (let i = 0; i < limit; i++) {
    const track = enriched[i];
    const needsArtwork = !track.artworkUrl?.startsWith("http") || track.artworkUrl?.includes("ytimg");
    if (!needsArtwork && track.explicit !== undefined) continue;
    try {
      const q = encodeURIComponent(`${track.artist} ${track.title}`);
      const res = await axios.get(`https://api.deezer.com/search/track?q=${q}&limit=1`, { timeout: 3000 });
      const data = res.data?.data?.[0];
      if (data) {
        if (data.album?.cover_medium) {
          track.artworkUrl = data.album.cover_medium;
          track.thumbnail = data.album.cover_medium;
        }
        if (data.explicit_lyrics !== undefined) track.explicit = data.explicit_lyrics;
      }
    } catch (e) {}
  }
  return enriched;
}

app.get("/api/spotify/search", requireApiKey, async (req, res) => {
  try {
    const q = req.query.q;
    const limit = Math.min(parseInt(req.query.limit) || 5, 20);
    if (!q) return res.status(400).json({ error: "Missing query parameter 'q'" });
    const tracks = await spotify.searchTracks(q, limit);
    res.json({ query: q, tracks, source: "spotify" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/spotify/search/albums", requireApiKey, async (req, res) => {
  try {
    const q = req.query.q;
    const limit = Math.min(parseInt(req.query.limit) || 5, 20);
    if (!q) return res.status(400).json({ error: "Missing query parameter 'q'" });
    const albums = await spotify.searchAlbums(q, limit);
    res.json({ query: q, albums, source: "spotify" });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

const WARM_CONCURRENCY = IS_RENDER ? 1 : 3;

app.post("/api/warm", requireApiKey, async (req, res) => {
  try {
    const { ids } = req.body;
    if (!Array.isArray(ids) || ids.length === 0) {
      return res.status(400).json({ error: "Missing or empty 'ids' array" });
    }

    const validIds = ids.filter(id => id && id !== "undefined" && id !== "null" && id.trim() !== "");
    res.json({ warmed: validIds.length });

    setImmediate(() => {
      const queue = validIds.slice();
      const workers = Array.from({ length: Math.min(WARM_CONCURRENCY, queue.length) }, async () => {
        while (queue.length > 0) {
          const id = queue.shift();
          try { await resolveStreamUrl(id, req); } catch (e) {}
        }
      });
      Promise.all(workers).catch(() => {});
    });
  } catch (err) {
    console.error("Warm Error:", err.message);
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/stream", requireApiKey, async (req, res) => {
  try {
    const { id, title, artist } = req.query;
    if (!id || id === "undefined" || id === "null" || id.trim() === "") {
      return res.status(400).json({ error: "Missing or invalid 'id' parameter" });
    }

    const getFinalStreamUrl = (url) => {
      if (!url) return url;
      
      // Si ya es un túnel de Cobalt, lo devolvemos directo (no es IP bound y ahorra recursos de Render)
      if (url.includes("mgytr.top") || url.includes("wolfy.love") || url.includes("clxxped.lol") || url.includes("qwkuns.me") || url.includes("cobalt")) {
        return url;
      }
      
      // Si es un stream directo de googlevideo (generado por yt-dlp/play-dl/Invidious), 
      // DEBEMOS proxyarlo a través del servidor porque las URLs de Google Video están atadas a la IP que las resolvió.
      if ((url.includes("googlevideo.com") || url.includes("youtube.com") || url.includes("youtu.be")) && req) {
        return `${req.protocol}://${req.get("host")}/api/proxy/audio?url=${encodeURIComponent(url)}`;
      }
      
      return url;
    };

    // (D) Fallback: URI de Deezer/Spotify → buscar en YTM por título+autor
    if (BAD_URI_REGEX.test(id)) {
      let query = null;
      if (title && artist) {
        query = `${artist} - ${title}`.trim();
      } else {
        // Buscar en DB por URL
        const found = await findLikedSongByUrl(id, "android") ||
                      await findLikedSongByUrl(id, "discord");
        if (found && found.track_title) {
          query = `${found.track_author || ""} - ${found.track_title}`.trim();
        }
      }
      if (query && query !== "-") {
        try {
          const tracks = await searchLavalink("ytmsearch", query);
          if (tracks.length) {
            const streamUrl = await resolveStreamUrl(tracks[0].uri, req);
            if (streamUrl) {
              return res.json({ url: getFinalStreamUrl(streamUrl), resolvedFrom: "ytm" });
            }
          }
        } catch (e) {
          console.warn("[stream] YTM fallback failed:", e.message);
        }
      }
      return res.status(404).json({ error: "Cannot resolve Deezer/Spotify URI" });
    }

    const streamUrl = await resolveStreamUrl(id, req);
    if (streamUrl) {
      return res.json({ url: getFinalStreamUrl(streamUrl) });
    }

    res.status(404).json({ error: "No stream found after fallback" });
  } catch (err) {
    console.error("Critical Stream Error:", err.stack);
    res.status(500).json({ error: "Server Internal Error" });
  }
});

// (C) Endpoint de migración: reemplaza URLs de Deezer/Spotify por YTM en MongoDB
app.post("/api/admin/migrate-liked-urls", requireApiKey, async (req, res) => {
  const sources = ["android", "discord"];
  const results = {};
  let totalGlobal = 0, updatedGlobal = 0, failedGlobal = 0;

  for (const source of sources) {
    let updated = 0, failed = 0;
    try {
      const badSongs = await getAllLikedSongsWithBadUrls(source);
      results[source] = { total: badSongs.length, updated: 0, failed: 0 };
      totalGlobal += badSongs.length;

      for (const song of badSongs) {
        const query = [
          song.track_author && song.track_title ? `${song.track_author} - ${song.track_title}` : null,
          song.track_title,
        ].filter(Boolean);

        let resolved = false;
        for (const q of query) {
          try {
            const tracks = await searchLavalink("ytmsearch", q);
            if (tracks.length && tracks[0].uri) {
              const ok = await updateLikedSongUrl(song._id, tracks[0].uri, source);
              if (ok) { updated++; resolved = true; break; }
            }
          } catch {}
        }
        if (!resolved) failed++;
      }
    } catch (e) {
      console.error(`[migrate] Error source=${source}:`, e.message);
      results[source] = results[source] || { total: 0, updated: 0, failed: 0 };
    }
    results[source].updated = updated;
    results[source].failed = failed;
    updatedGlobal += updated;
    failedGlobal += failed;
  }

  res.json({ total: totalGlobal, updated: updatedGlobal, failed: failedGlobal, bySource: results });
});

app.get("/api/lyrics", requireApiKey, async (req, res) => {
  try {
    const { track, artist, album } = req.query;
    if (!track) return res.status(400).json({ error: "Missing 'track' parameter" });
    const result = await getLyrics(track, artist || "", album || "");
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/likes/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const songs = await db.getLikedSongs(userId, parseInt(req.query.limit) || 0, source);
    res.json({ count: songs.length, songs });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/likes/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const { trackTitle, trackAuthor, trackUrl, trackDuration, artworkUrl, isrc, explicit, genres } = req.body;
    const mockTrack = {
      info: { title: trackTitle, author: trackAuthor, uri: trackUrl || "", duration: trackDuration || 0, artworkUrl: artworkUrl || "", explicit: explicit === true, genres: genres || [] },
      pluginInfo: { isrc: isrc || null }
    };
    const added = await db.addLikedSong(userId, mockTrack, source);
    res.json({ added });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.delete("/api/likes/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const { trackUrl } = req.body;
    const mockTrack = { info: { uri: trackUrl } };
    const removed = await db.removeLikedSongByTrack(userId, mockTrack, source);
    res.json({ removed });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Liked Albums ─────────────────────────────────────────────────────
app.get("/api/albums/liked", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId;
    const source = req.provider || "android";
    if (!userId) return res.status(401).json({ error: "Unauthorized" });
    const albums = await db.getLikedAlbums(userId, source);
    res.json({ albums });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/albums/like", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId;
    const source = req.provider || "android";
    if (!userId) return res.status(401).json({ error: "Unauthorized" });
    const { albumId, albumName, artistName, artworkUrl, albumUrl } = req.body;
    if (!albumId) return res.status(400).json({ error: "albumId is required" });
    const result = await db.toggleLikeAlbum(userId, { albumId, albumName, artistName, artworkUrl, albumUrl }, source);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/albums/liked/check", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId;
    const source = req.provider || "android";
    if (!userId) return res.status(401).json({ error: "Unauthorized" });
    const { albumId } = req.query;
    if (!albumId) return res.status(400).json({ error: "albumId query param is required" });
    const liked = await db.isAlbumLiked(userId, albumId, source);
    res.json({ liked });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Followed Artists ─────────────────────────────────────────────────
app.get("/api/artists/followed", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId;
    const source = req.provider || "android";
    if (!userId) return res.status(401).json({ error: "Unauthorized" });
    const artists = await db.getFollowedArtists(userId, source);
    res.json({ artists });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/artists/follow", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId;
    const source = req.provider || "android";
    if (!userId) return res.status(401).json({ error: "Unauthorized" });
    const { artistId, artistName, imageUrl } = req.body;
    if (!artistId) return res.status(400).json({ error: "artistId is required" });
    const result = await db.toggleFollowArtist(userId, { artistId, artistName, imageUrl }, source);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/artists/followed/check", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId;
    const source = req.provider || "android";
    if (!userId) return res.status(401).json({ error: "Unauthorized" });
    const { artistId } = req.query;
    if (!artistId) return res.status(400).json({ error: "artistId query param is required" });
    const followed = await db.isArtistFollowed(userId, artistId, source);
    res.json({ followed });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/stats/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const stats = await db.getUserStats(userId, source);
    res.json({ stats });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/playlists/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const playlists = await db.getUserPlaylists(userId, source);
    res.json({ playlists });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/playlists/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const { name, tracks } = req.body;
    const id = await db.savePlaylist(userId, name, tracks, source);
    res.json({ id });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/artists/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const artists = await db.getLikedArtists(userId, source);
    res.json({ artists });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/artist-image", requireApiKey, async (req, res) => {
  try {
    const name = req.query.name;
    if (!name) return res.status(400).json({ error: "Missing 'name'" });
    const deezerRes = await axios.get(`https://api.deezer.com/search/artist?q=${encodeURIComponent(name)}&limit=1`);
    const url = deezerRes.data?.data?.[0]?.picture_medium || null;
    res.json({ url });
  } catch (err) {
    res.json({ url: null });
  }
});

app.get("/api/recommendations/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const liked = await db.getLikedSongs(userId, 5, source);
    if (!liked.length) return res.json({ tracks: [] });
    const spotifyTracks = await spotify.searchTracks(`${liked[0].track_title} ${liked[0].track_author}`, 5);
    const seedIds = spotifyTracks.map(t => t.id).filter(Boolean).slice(0, 5);
    const recs = seedIds.length ? await spotify.getRecommendations(seedIds) : [];
    res.json({ tracks: recs });
  } catch (err) {
    res.json({ tracks: [] });
  }
});

app.get("/api/top-tracks/:userId", requireApiKey, async (req, res) => {
  try {
    const userId = req.userId || req.params.userId;
    const source = req.provider || "android";
    const tracks = await db.getMostPlayedTracks(userId, parseInt(req.query.limit) || 10, source);
    res.json({ tracks });
  } catch (err) {
    res.json({ tracks: [] });
  }
});

// ── Auth routes ──────────────────────────────────────────────────────
const JWT_SECRET = process.env.JWT_SECRET || "dev-secret-change-in-production";
const JWT_EXPIRES = "30d";

function signToken(user, provider = "android") {
  const payload = { sub: user._id.toString(), provider };
  if (provider === "discord" && user.discordId) {
    payload.discordId = user.discordId;
  }
  return jwt.sign(payload, JWT_SECRET, { expiresIn: JWT_EXPIRES });
}

// ── Discord OAuth Strategy ────────────────────────────────────────────
passport.use(new DiscordStrategy({
  clientID: process.env.DISCORD_CLIENT_ID,
  clientSecret: process.env.DISCORD_CLIENT_SECRET,
  callbackURL: process.env.DISCORD_CALLBACK_URL || "http://192.168.18.81:3000/api/auth/discord/callback",
  scope: ["identify", "email"],
}, async (accessToken, refreshToken, profile, done) => {
  try {
    if (!DiscordUser) return done(new Error("Discord database not configured"));
    let user = await DiscordUser.findOne({ discordId: profile.id });
    if (user) return done(null, user);

    const email = profile.email || null;
    if (email) {
      user = await DiscordUser.findOne({ email });
      if (user) {
        user.discordId = profile.id;
        if (!user.avatar && profile.avatar) user.avatar = `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.png`;
        await user.save();
        return done(null, user);
      }
    }

    user = await DiscordUser.create({
      username: profile.username || profile.global_name || `discord_${profile.id}`,
      email,
      discordId: profile.id,
      avatar: profile.avatar ? `https://cdn.discordapp.com/avatars/${profile.id}/${profile.avatar}.png` : "",
    });
    return done(null, user);
  } catch (err) {
    return done(err);
  }
}));

// ── Google OAuth Strategy ─────────────────────────────────────────────
passport.use(new GoogleStrategy({
  clientID: process.env.GOOGLE_CLIENT_ID,
  clientSecret: process.env.GOOGLE_CLIENT_SECRET,
  callbackURL: process.env.GOOGLE_CALLBACK_URL || "/api/auth/google/callback",
  scope: ["profile", "email"],
}, async (accessToken, refreshToken, profile, done) => {
  try {
    // 1. Buscar por googleId
    let user = await User.findOne({ googleId: profile.id });
    if (user) return done(null, user);

    // 2. Si tiene email, buscar si ya existe la cuenta y vincularla
    const email = profile.emails?.[0]?.value || null;
    if (email) {
      user = await User.findOne({ email });
      if (user) {
        user.googleId = profile.id;
        if (!user.avatar && profile.photos?.[0]?.value) {
          user.avatar = profile.photos[0].value;
        }
        await user.save();
        return done(null, user);
      }
    }

    // 3. Crear nuevo usuario
    user = await User.create({
      username: profile.displayName || profile.name?.givenName || `google_${profile.id}`,
      email,
      googleId: profile.id,
      avatar: profile.photos?.[0]?.value || "",
    });
    return done(null, user);
  } catch (err) {
    return done(err);
  }
}));

app.post("/api/auth/register", async (req, res) => {
  try {
    const { username, email, password } = req.body;
    if (!username || !email || !password) {
      return res.status(400).json({ error: "username, email, and password are required" });
    }

    const existing = await User.findOne({ email: email.toLowerCase() }).exec();
    if (existing) {
      return res.status(409).json({ error: "Email already registered" });
    }

    const user = await User.create({ username, email: email.toLowerCase(), password });
    const token = signToken(user);
    res.status(201).json({ token, user: user.toPublicJSON() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/auth/login", async (req, res) => {
  try {
    const { email, password } = req.body;
    if (!email || !password) {
      return res.status(400).json({ error: "email and password are required" });
    }

    const user = await User.findOne({ email: email.toLowerCase() }).exec();
    if (!user || !user.password) {
      return res.status(401).json({ error: "Invalid email or password" });
    }

    const match = await bcrypt.compare(password, user.password);
    if (!match) {
      return res.status(401).json({ error: "Invalid email or password" });
    }

    const token = signToken(user);
    res.json({ token, user: user.toPublicJSON() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/auth/me", requireAuth, async (req, res) => {
  try {
    const UserModel = req.provider === "discord" && DiscordUser ? DiscordUser : User;
    const user = await UserModel.findById(req.mongoId).exec();
    if (!user) return res.status(404).json({ error: "User not found" });
    res.json({ user: user.toPublicJSON() });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Discord OAuth routes ──────────────────────────────────────────────
app.get("/api/auth/discord", passport.authenticate("discord", { session: false }));

app.get("/api/auth/discord/callback", (req, res, next) => {
  passport.authenticate("discord", { session: false }, (err, user) => {
    if (err || !user) {
      const url = process.env.CLIENT_URL || "musicapp://auth";
      return res.redirect(`${url}?error=auth_failed`);
    }
    const token = signToken(user, "discord");
    const url = process.env.CLIENT_URL || "musicapp://auth";
    res.redirect(`${url}?token=${token}`);
  })(req, res, next);
});

// ── Google OAuth routes ───────────────────────────────────────────────
// Endpoint para Android (Native Google Sign-In)
app.post("/api/auth/google", async (req, res) => {
  try {
    const { id_token } = req.body;
    const idToken = id_token || req.body.idToken; // Soporta ambos formatos por si acaso

    if (!idToken) return res.status(400).json({ error: "idToken is required" });

    // Verificar token con Google API (Sin librerías extra)
    const googleRes = await axios.get(`https://oauth2.googleapis.com/tokeninfo?id_token=${idToken}`);
    const payload = googleRes.data;

    if (!payload || googleRes.status !== 200) {
      return res.status(401).json({ error: "Invalid Google token" });
    }

    const { sub: googleId, email, name, picture } = payload;

    // 1. Buscar o vincular usuario
    let user = await User.findOne({ $or: [{ googleId }, { email }] });

    if (!user) {
      user = await User.create({
        username: name || `google_${googleId}`,
        email,
        googleId,
        avatar: picture || "",
      });
    } else if (!user.googleId) {
      user.googleId = googleId;
      if (!user.avatar) user.avatar = picture || "";
      await user.save();
    }

    // 2. Generar JWT y responder
    const token = signToken(user);
    res.json({ token, user: user.toPublicJSON() });

  } catch (err) {
    console.error("[Google Auth POST] Error:", err.response?.data || err.message);
    res.status(401).json({ error: "Google authentication failed" });
  }
});

app.get("/api/auth/google",
  passport.authenticate("google", { session: false, scope: ["profile", "email"] })
);

app.get("/api/auth/google/callback", (req, res, next) => {
  passport.authenticate("google", { session: false }, (err, user) => {
    const clientUrl = process.env.CLIENT_URL || "musicapp://auth";
    if (err || !user) {
      console.error("[Google OAuth] Error:", err?.message);
      return res.redirect(`${clientUrl}?error=auth_failed&provider=google`);
    }
    const token = signToken(user);
    return res.redirect(`${clientUrl}?token=${token}&provider=google`);
  })(req, res, next);
});

// Global error handler
app.use(function (err, req, res, next) {
  console.error("[ERROR] global handler:", err.stack || err);
  res.status(500).json({ error: err.message || "Internal server error" });
});

module.exports = { app };
